-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object exposing (Business(..), BusinessMessaging(..), Businesses(..), Categories(..), Category(..), Coordinates(..), Country(..), Event(..), Events(..), Hours(..), Language(..), Locale(..), Location(..), OpenHours(..), RestaurantReservations(..), Review(..), Reviews(..), SpecialHours(..), Transactions(..), User(..))


type Business
    = Business


type BusinessMessaging
    = BusinessMessaging


type Businesses
    = Businesses


type Categories
    = Categories


type Category
    = Category


type Coordinates
    = Coordinates


type Country
    = Country


type Event
    = Event


type Events
    = Events


type Hours
    = Hours


type Language
    = Language


type Locale
    = Locale


type Location
    = Location


type OpenHours
    = OpenHours


type RestaurantReservations
    = RestaurantReservations


type Review
    = Review


type Reviews
    = Reviews


type SpecialHours
    = SpecialHours


type Transactions
    = Transactions


type User
    = User
