-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.ScalarCodecs exposing (Date, GenericScalar, codecs)

import Json.Decode as Decode exposing (Decoder)
import YelpApi.Scalar exposing (defaultCodecs)


type alias Date =
    YelpApi.Scalar.Date


type alias GenericScalar =
    YelpApi.Scalar.GenericScalar


codecs : YelpApi.Scalar.Codecs Date GenericScalar
codecs =
    YelpApi.Scalar.defineCodecs
        { codecDate = defaultCodecs.codecDate
        , codecGenericScalar = defaultCodecs.codecGenericScalar
        }
