-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Business exposing (ReviewsOptionalArguments, alias, attributes, categories, coordinates, display_phone, distance, hours, id, is_claimed, is_closed, location, messaging, name, phone, photos, price, rating, review_count, reviews, special_hours, transactions, url)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Name of this business.
-}
name : SelectionSet (Maybe String) YelpApi.Object.Business
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| Yelp ID of this business.
-}
id : SelectionSet (Maybe String) YelpApi.Object.Business
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


{-| Yelp alias of this business.
-}
alias : SelectionSet (Maybe String) YelpApi.Object.Business
alias =
    Object.selectionForField "(Maybe String)" "alias" [] (Decode.string |> Decode.nullable)


{-| Whether business has been claimed by a business owner.
-}
is_claimed : SelectionSet (Maybe Bool) YelpApi.Object.Business
is_claimed =
    Object.selectionForField "(Maybe Bool)" "is_claimed" [] (Decode.bool |> Decode.nullable)


{-| Whether business has been (permanently) closed.
-}
is_closed : SelectionSet (Maybe Bool) YelpApi.Object.Business
is_closed =
    Object.selectionForField "(Maybe Bool)" "is_closed" [] (Decode.bool |> Decode.nullable)


{-| URL for business page on Yelp.
-}
url : SelectionSet (Maybe String) YelpApi.Object.Business
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


{-| Phone number of the business.
-}
phone : SelectionSet (Maybe String) YelpApi.Object.Business
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


{-| Phone number of the business formatted nicely to be displayed to users. The format is the standard phone number format for the business's country.
-}
display_phone : SelectionSet (Maybe String) YelpApi.Object.Business
display_phone =
    Object.selectionForField "(Maybe String)" "display_phone" [] (Decode.string |> Decode.nullable)


{-| Number of reviews for this business.
-}
review_count : SelectionSet (Maybe Int) YelpApi.Object.Business
review_count =
    Object.selectionForField "(Maybe Int)" "review_count" [] (Decode.int |> Decode.nullable)


{-| A list of category title and alias pairs associated with this business.
-}
categories : SelectionSet decodesTo YelpApi.Object.Category -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Business
categories object_ =
    Object.selectionForCompositeField "categories" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Rating for this business (value ranges from 1, 1.5, ... 4.5, 5).
-}
rating : SelectionSet (Maybe Float) YelpApi.Object.Business
rating =
    Object.selectionForField "(Maybe Float)" "rating" [] (Decode.float |> Decode.nullable)


{-| Price level of the business. Value is one of $, $$, $$$ and $$$$ or null if we don't have price available for the business.
-}
price : SelectionSet (Maybe String) YelpApi.Object.Business
price =
    Object.selectionForField "(Maybe String)" "price" [] (Decode.string |> Decode.nullable)


{-| The location of this business, including address, city, state, zip code and country.
-}
location : SelectionSet decodesTo YelpApi.Object.Location -> SelectionSet (Maybe decodesTo) YelpApi.Object.Business
location object_ =
    Object.selectionForCompositeField "location" [] object_ (identity >> Decode.nullable)


{-| The coordinates of this business.
-}
coordinates : SelectionSet decodesTo YelpApi.Object.Coordinates -> SelectionSet (Maybe decodesTo) YelpApi.Object.Business
coordinates object_ =
    Object.selectionForCompositeField "coordinates" [] object_ (identity >> Decode.nullable)


{-| URLs of up to three photos of the business.
-}
photos : SelectionSet (Maybe (List (Maybe String))) YelpApi.Object.Business
photos =
    Object.selectionForField "(Maybe (List (Maybe String)))" "photos" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Opening hours of the business.
-}
hours : SelectionSet decodesTo YelpApi.Object.Hours -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Business
hours object_ =
    Object.selectionForCompositeField "hours" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Special hours of the business, these override regular opening hours of the business.
-}
special_hours : SelectionSet decodesTo YelpApi.Object.SpecialHours -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Business
special_hours object_ =
    Object.selectionForCompositeField "special_hours" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


type alias ReviewsOptionalArguments =
    { limit : OptionalArgument Int
    , offset : OptionalArgument Int
    }


{-| Review snippets from the business.
-}
reviews : (ReviewsOptionalArguments -> ReviewsOptionalArguments) -> SelectionSet decodesTo YelpApi.Object.Review -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Business
reviews fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { limit = Absent, offset = Absent }

        optionalArgs =
            [ Argument.optional "limit" filledInOptionals.limit Encode.int, Argument.optional "offset" filledInOptionals.offset Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "reviews" optionalArgs object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| When searching, this provides the distance of the business from the search location in meters
-}
distance : SelectionSet (Maybe Float) YelpApi.Object.Business
distance =
    Object.selectionForField "(Maybe Float)" "distance" [] (Decode.float |> Decode.nullable)


{-| Business attributes, if available.
-}
attributes : SelectionSet (Maybe YelpApi.ScalarCodecs.GenericScalar) YelpApi.Object.Business
attributes =
    Object.selectionForField "(Maybe ScalarCodecs.GenericScalar)" "attributes" [] (YelpApi.ScalarCodecs.codecs |> YelpApi.Scalar.unwrapCodecs |> .codecGenericScalar |> .decoder |> Decode.nullable)


{-| Information and action links for transacting with this business online.
-}
transactions : SelectionSet decodesTo YelpApi.Object.Transactions -> SelectionSet (Maybe decodesTo) YelpApi.Object.Business
transactions object_ =
    Object.selectionForCompositeField "transactions" [] object_ (identity >> Decode.nullable)


{-| Information and action links for messaging with this business via Yelp, including requesting quotes.
-}
messaging : SelectionSet decodesTo YelpApi.Object.BusinessMessaging -> SelectionSet (Maybe decodesTo) YelpApi.Object.Business
messaging object_ =
    Object.selectionForCompositeField "messaging" [] object_ (identity >> Decode.nullable)
