-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.BusinessMessaging exposing (url, use_case_text)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Visit this action link URL to go directly into the business messaging flow for this business.
-}
url : SelectionSet (Maybe String) YelpApi.Object.BusinessMessaging
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


{-| The localized text description of the type of messaging this business is enabled for. Example: "Request a Quote"
-}
use_case_text : SelectionSet (Maybe String) YelpApi.Object.BusinessMessaging
use_case_text =
    Object.selectionForField "(Maybe String)" "use_case_text" [] (Decode.string |> Decode.nullable)
