-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Businesses exposing (business, total)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| A list of business Yelp finds based on the search criteria.
-}
business : SelectionSet decodesTo YelpApi.Object.Business -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Businesses
business object_ =
    Object.selectionForCompositeField "business" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Total number of businesses found.
-}
total : SelectionSet (Maybe Int) YelpApi.Object.Businesses
total =
    Object.selectionForField "(Maybe Int)" "total" [] (Decode.int |> Decode.nullable)
