-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Categories exposing (category, total)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| The category objects.
-}
category : SelectionSet decodesTo YelpApi.Object.Category -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Categories
category object_ =
    Object.selectionForCompositeField "category" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Total number of categories.
-}
total : SelectionSet (Maybe Int) YelpApi.Object.Categories
total =
    Object.selectionForField "(Maybe Int)" "total" [] (Decode.int |> Decode.nullable)
