-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Category exposing (alias, country_blacklist, country_whitelist, parent_categories, title)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Title of a category for display purposes.
-}
title : SelectionSet (Maybe String) YelpApi.Object.Category
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


{-| Alias of a category, when searching for business in certain categories, use alias rather than the title.
-}
alias : SelectionSet (Maybe String) YelpApi.Object.Category
alias =
    Object.selectionForField "(Maybe String)" "alias" [] (Decode.string |> Decode.nullable)


{-| List of parent categories.
-}
parent_categories : SelectionSet decodesTo YelpApi.Object.Category -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Category
parent_categories object_ =
    Object.selectionForCompositeField "parent_categories" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Countries for which this category is whitelisted.
-}
country_whitelist : SelectionSet decodesTo YelpApi.Object.Country -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Category
country_whitelist object_ =
    Object.selectionForCompositeField "country_whitelist" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Countries for which this category is blacklisted.
-}
country_blacklist : SelectionSet decodesTo YelpApi.Object.Country -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Category
country_blacklist object_ =
    Object.selectionForCompositeField "country_blacklist" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
