-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Event exposing (attending_count, business, business_id, category, cost, cost_max, description, event_site_url, id, image_url, interested_count, is_canceled, is_free, is_official, latitude, location, longitude, name, tickets_url, time_end, time_start)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Name of this event.
-}
name : SelectionSet (Maybe String) YelpApi.Object.Event
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| Event id.
-}
id : SelectionSet (Maybe String) YelpApi.Object.Event
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


{-| The business tied to this event.
-}
business : SelectionSet decodesTo YelpApi.Object.Business -> SelectionSet (Maybe decodesTo) YelpApi.Object.Event
business object_ =
    Object.selectionForCompositeField "business" [] object_ (identity >> Decode.nullable)


{-| The ID of the related business.
-}
business_id : SelectionSet (Maybe String) YelpApi.Object.Event
business_id =
    Object.selectionForField "(Maybe String)" "business_id" [] (Decode.string |> Decode.nullable)


{-| Number of Yelp users attending this event.
-}
attending_count : SelectionSet (Maybe String) YelpApi.Object.Event
attending_count =
    Object.selectionForField "(Maybe String)" "attending_count" [] (Decode.string |> Decode.nullable)


{-| The category of this event.
-}
category : SelectionSet (Maybe String) YelpApi.Object.Event
category =
    Object.selectionForField "(Maybe String)" "category" [] (Decode.string |> Decode.nullable)


{-| Cost of attending this event.
-}
cost : SelectionSet (Maybe Int) YelpApi.Object.Event
cost =
    Object.selectionForField "(Maybe Int)" "cost" [] (Decode.int |> Decode.nullable)


{-| Maximum cost of this event.
-}
cost_max : SelectionSet (Maybe Int) YelpApi.Object.Event
cost_max =
    Object.selectionForField "(Maybe Int)" "cost_max" [] (Decode.int |> Decode.nullable)


{-| Description excerpt of this event.
-}
description : SelectionSet (Maybe String) YelpApi.Object.Event
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| Yelp page of this event.
-}
event_site_url : SelectionSet (Maybe String) YelpApi.Object.Event
event_site_url =
    Object.selectionForField "(Maybe String)" "event_site_url" [] (Decode.string |> Decode.nullable)


{-| Yelp image url of this event.
-}
image_url : SelectionSet (Maybe String) YelpApi.Object.Event
image_url =
    Object.selectionForField "(Maybe String)" "image_url" [] (Decode.string |> Decode.nullable)


{-| Number of Yelp users interested in attending this event.
-}
interested_count : SelectionSet (Maybe String) YelpApi.Object.Event
interested_count =
    Object.selectionForField "(Maybe String)" "interested_count" [] (Decode.string |> Decode.nullable)


{-| Whether this event is canceled.
-}
is_canceled : SelectionSet (Maybe Bool) YelpApi.Object.Event
is_canceled =
    Object.selectionForField "(Maybe Bool)" "is_canceled" [] (Decode.bool |> Decode.nullable)


{-| Whether this event is free.
-}
is_free : SelectionSet (Maybe Bool) YelpApi.Object.Event
is_free =
    Object.selectionForField "(Maybe Bool)" "is_free" [] (Decode.bool |> Decode.nullable)


{-| Whether this event is created by a Yelp community manager.
-}
is_official : SelectionSet (Maybe Bool) YelpApi.Object.Event
is_official =
    Object.selectionForField "(Maybe Bool)" "is_official" [] (Decode.bool |> Decode.nullable)


{-| Latitude of this event.
-}
latitude : SelectionSet (Maybe Float) YelpApi.Object.Event
latitude =
    Object.selectionForField "(Maybe Float)" "latitude" [] (Decode.float |> Decode.nullable)


{-| Longitude of this event.
-}
longitude : SelectionSet (Maybe Float) YelpApi.Object.Event
longitude =
    Object.selectionForField "(Maybe Float)" "longitude" [] (Decode.float |> Decode.nullable)


{-| The location of this business, including address, city, state, postal code and country.
-}
location : SelectionSet decodesTo YelpApi.Object.Location -> SelectionSet (Maybe decodesTo) YelpApi.Object.Event
location object_ =
    Object.selectionForCompositeField "location" [] object_ (identity >> Decode.nullable)


{-| URL to buy tickets for this event.
-}
tickets_url : SelectionSet (Maybe String) YelpApi.Object.Event
tickets_url =
    Object.selectionForField "(Maybe String)" "tickets_url" [] (Decode.string |> Decode.nullable)


{-| Time this event ends. Returns time and date in the following format - "YYYY-MM-DD HH-mm".
-}
time_end : SelectionSet (Maybe String) YelpApi.Object.Event
time_end =
    Object.selectionForField "(Maybe String)" "time_end" [] (Decode.string |> Decode.nullable)


{-| Time the event starts. Returns time and date in the following format - "YYYY-MM-DD HH-mm".
-}
time_start : SelectionSet (Maybe String) YelpApi.Object.Event
time_start =
    Object.selectionForField "(Maybe String)" "time_start" [] (Decode.string |> Decode.nullable)
