-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Hours exposing (hours_type, is_open_now, open)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| The type of the opening hours information. Right now, this is always REGULAR.
-}
hours_type : SelectionSet (Maybe String) YelpApi.Object.Hours
hours_type =
    Object.selectionForField "(Maybe String)" "hours_type" [] (Decode.string |> Decode.nullable)


{-| The specific open hours and days for a business.
-}
open : SelectionSet decodesTo YelpApi.Object.OpenHours -> SelectionSet (Maybe (List (Maybe decodesTo))) YelpApi.Object.Hours
open object_ =
    Object.selectionForCompositeField "open" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Describes if the business is open now.
-}
is_open_now : SelectionSet (Maybe Bool) YelpApi.Object.Hours
is_open_now =
    Object.selectionForField "(Maybe Bool)" "is_open_now" [] (Decode.bool |> Decode.nullable)
