-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Locale exposing (code, country, language)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| The code for this locale, in the format of {language\_code}_{country_code}.
-}
code : SelectionSet (Maybe String) YelpApi.Object.Locale
code =
    Object.selectionForField "(Maybe String)" "code" [] (Decode.string |> Decode.nullable)


{-| The language component of this locale.
-}
language : SelectionSet decodesTo YelpApi.Object.Language -> SelectionSet (Maybe decodesTo) YelpApi.Object.Locale
language object_ =
    Object.selectionForCompositeField "language" [] object_ (identity >> Decode.nullable)


{-| The country component of this locale.
-}
country : SelectionSet decodesTo YelpApi.Object.Country -> SelectionSet (Maybe decodesTo) YelpApi.Object.Locale
country object_ =
    Object.selectionForCompositeField "country" [] object_ (identity >> Decode.nullable)
