-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Location exposing (address1, address2, address3, city, country, formatted_address, postal_code, state)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Street address of this business.
-}
address1 : SelectionSet (Maybe String) YelpApi.Object.Location
address1 =
    Object.selectionForField "(Maybe String)" "address1" [] (Decode.string |> Decode.nullable)


{-| Street address of this business, continued.
-}
address2 : SelectionSet (Maybe String) YelpApi.Object.Location
address2 =
    Object.selectionForField "(Maybe String)" "address2" [] (Decode.string |> Decode.nullable)


{-| Street address of this business, continued.
-}
address3 : SelectionSet (Maybe String) YelpApi.Object.Location
address3 =
    Object.selectionForField "(Maybe String)" "address3" [] (Decode.string |> Decode.nullable)


{-| City of this business.
-}
city : SelectionSet (Maybe String) YelpApi.Object.Location
city =
    Object.selectionForField "(Maybe String)" "city" [] (Decode.string |> Decode.nullable)


{-| ISO 3166-2 (with a few exceptions) state code of this business.
-}
state : SelectionSet (Maybe String) YelpApi.Object.Location
state =
    Object.selectionForField "(Maybe String)" "state" [] (Decode.string |> Decode.nullable)


{-| Postal code of this business.
-}
postal_code : SelectionSet (Maybe String) YelpApi.Object.Location
postal_code =
    Object.selectionForField "(Maybe String)" "postal_code" [] (Decode.string |> Decode.nullable)


{-| ISO 3166-1 alpha-2 country code of this business.
-}
country : SelectionSet (Maybe String) YelpApi.Object.Location
country =
    Object.selectionForField "(Maybe String)" "country" [] (Decode.string |> Decode.nullable)


{-| Array of strings that if organized vertically give an address that is in the standard address format for the business's country.
-}
formatted_address : SelectionSet (Maybe String) YelpApi.Object.Location
formatted_address =
    Object.selectionForField "(Maybe String)" "formatted_address" [] (Decode.string |> Decode.nullable)
