-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.OpenHours exposing (day, end, is_overnight, start)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Whether the business opens overnight or not. When this is true, the end time will be lower than the start time.
-}
is_overnight : SelectionSet (Maybe Bool) YelpApi.Object.OpenHours
is_overnight =
    Object.selectionForField "(Maybe Bool)" "is_overnight" [] (Decode.bool |> Decode.nullable)


{-| End of the opening hours in a day, in 24-hour clock notation, like 2130 means 9:30 PM.
-}
end : SelectionSet (Maybe String) YelpApi.Object.OpenHours
end =
    Object.selectionForField "(Maybe String)" "end" [] (Decode.string |> Decode.nullable)


{-| Start of the opening hours in a day, in 24-hour clock notation, like 1000 means 10 AM.
-}
start : SelectionSet (Maybe String) YelpApi.Object.OpenHours
start =
    Object.selectionForField "(Maybe String)" "start" [] (Decode.string |> Decode.nullable)


{-| From 0 to 6, representing day of the week from Monday to Sunday. Notice that you may get the same day of the week more than once if the business has more than one opening time slots.
-}
day : SelectionSet (Maybe Int) YelpApi.Object.OpenHours
day =
    Object.selectionForField "(Maybe Int)" "day" [] (Decode.int |> Decode.nullable)
