-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.Transactions exposing (restaurant_reservations)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| Online reservations via Yelp Reservations.
-}
restaurant_reservations : SelectionSet decodesTo YelpApi.Object.RestaurantReservations -> SelectionSet (Maybe decodesTo) YelpApi.Object.Transactions
restaurant_reservations object_ =
    Object.selectionForCompositeField "restaurant_reservations" [] object_ (identity >> Decode.nullable)
