-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Object.User exposing (id, image_url, name, profile_url)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import YelpApi.InputObject
import YelpApi.Interface
import YelpApi.Object
import YelpApi.Scalar
import YelpApi.ScalarCodecs
import YelpApi.Union


{-| The User's ID, a 22 character string
-}
id : SelectionSet (Maybe String) YelpApi.Object.User
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


{-| User's profile url
-}
profile_url : SelectionSet (Maybe String) YelpApi.Object.User
profile_url =
    Object.selectionForField "(Maybe String)" "profile_url" [] (Decode.string |> Decode.nullable)


{-| URL of the user's profile photo.
-}
image_url : SelectionSet (Maybe String) YelpApi.Object.User
image_url =
    Object.selectionForField "(Maybe String)" "image_url" [] (Decode.string |> Decode.nullable)


{-| Name of the user.
-}
name : SelectionSet (Maybe String) YelpApi.Object.User
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
