-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module YelpApi.Enum.MatchThreshold exposing (MatchThreshold(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| An enumeration.
-}
type MatchThreshold
    = None
    | Default
    | Strict


list : List MatchThreshold
list =
    [ None, Default, Strict ]


decoder : Decoder MatchThreshold
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NONE" ->
                        Decode.succeed None

                    "DEFAULT" ->
                        Decode.succeed Default

                    "STRICT" ->
                        Decode.succeed Strict

                    _ ->
                        Decode.fail ("Invalid MatchThreshold type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : MatchThreshold -> String
toString enum =
    case enum of
        None ->
            "NONE"

        Default ->
            "DEFAULT"

        Strict ->
            "STRICT"
